%function to filter data from 50Hz and baseline noise
% Decompose Signal using the MODWT
% Generated by MATLAB(R) 9.9 and Wavelet Toolbox 5.5.
% Generated on: 09-Sep-2021 17:18:04
% Logical array for selecting reconstruction elements
function cleanSignal = waveletFilter(rawSignal)
levelForReconstruction = [false, false, false, false, true, true, true, true, true, false, false];
% Perform the decomposition using modwt
wt = modwt(rawSignal, 'sym4', 10);
% Construct MRA matrix using modwtmra
mra = modwtmra(wt, 'sym4');
% Sum along selected multiresolution signals
cleanSignal = sum(mra(levelForReconstruction,:),1);
end
